# Site settings
author: Osi Ejedawe
title: Code to Freedom
header-img: img/home-bg.png
email: osi.ejedawe@hotmail.com
copyright_name: Osi Ejedawe
description: > # this means to ignore newlines until "baseurl:"
  Achieving Success
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hovablack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
